devsoc-unsw/chaos

backend/src/auth.rs, frontend/src/pages/auth_success/index.js, frontend/src/pages/landing/index.js
Allows a user to: 
- SignUp with google OAUTH
- SignIn with google OAUTH
- Users signed in witll go straight to dashboard
=> CHAOS-6 Login Flow

backend/src/main.rs, backend/src/user.rs
New route added - with mounting in main.rs and route in user.rs"
=> Get User from Id route added "/user/<user_id>"

backend/src/campaigns.rs
small PR to fix comment positioning
=> CHAOS-32 fix campaign docs

backend/src/campaigns.rs, backend/src/database/models.rs, backend/src/main.rs, backend/src/user.rs
```
GET /user/campaigns
```
Returns a vec of details of the campaign (id, org_id, name, cover, description, start, end, draft) that a user has applied for in past/is currently applying for
```
GET /campaigns/all
```
Returns a vec of all current campaigns that have either started, or are not in draft phase (ie, if someone published their campaign early)
=> /user/campaigns and /campaigns/all

frontend/.env.development, frontend/.gitignore
no secrets were harmed in the making of this PR
=> frontend only xd

frontend/src/components/AdminContent/AdminCampaignContent.js, frontend/src/components/AdminContent/AdminMembersContent.js, frontend/src/components/AdminContent/adminContent.styled.js, frontend/src/components/AdminContent/index.js, frontend/src/components/AdminSideBar/adminSidebar.styled.js, frontend/src/components/AdminSideBar/index.js, frontend/src/pages/admin/admin.styled.js, frontend/src/pages/admin/index.js
Had to resubmit PR cause I made style changes in 2 separate commits :(
=> Added campaigns + members content to admin page

frontend/src/pages/signup/index.js
starting year was being sent as string, not int - and failing backend validation
=> fix starting year bug

backend/server/src/bin.rs, backend/server/src/database/models.rs, backend/server/src/role.rs
Made a new branch for CHAOS-42 since the old branch is super outdated and merging would be a massive effort. I know this isn't best practices but there isn't that much changed so its surely fine :))
=> Transferred stuff from old CHAOS-42 branch here

backend/server/src/bin.rs, backend/server/src/organisation.rs
Very simple function to check whether a user is an admin (AdminLevel == Admin || user.superuser) in a given organisation.
=> Finished CHAOS-70

frontend/package.json, frontend/yarn.lock
=> [CHAOS-73] eslint dependency fix

frontend/src/pages/dashboard/CampaignGrid/index.js, frontend/src/pages/dashboard/index.js, frontend/src/utils/index.js
Use the campaign data fetched from the backend in the dashboard, instead of dummy data. This also refactors this page using a separate CampaignGrid component to reduce repetition
=> [CHAOS-50] integrate dashboard with backend

frontend/src/components/AdminContent/AdminCampaignContent.js
Link to marking page using the campaign id in the url so that navigation works properly, now that the marking page uses it now
=> [CHAOS-95] Fix campaign links from admin dashboard

frontend/babel.config.json, frontend/package.json, frontend/yarn.lock
This just adds a babel config for the frontend with some reasonable presets and targets
=> [CHAOS-123] fix babel config error

backend/server/src/application.rs, backend/server/src/auth.rs, backend/server/src/database/models.rs, backend/server/src/question.rs
I have no idea what im doing xdddd
=> [CHAOS-125] Check whether answers are valid in application.rs submit_answer function

backend/server/src/application.rs, backend/server/src/auth.rs, backend/server/src/database/models.rs, backend/server/src/question.rs
=> [CHAOS-124] route for changing the status of an application

frontend/src/components/CampaignCard/index.js, frontend/src/pages/dashboard/CampaignGrid/index.js, frontend/src/utils/index.js
use the application status from the backend for the thingies
=> [CHAOS-116] fix application status chips in campaign cards on dashboard

frontend/src/pages/admin/AdminContent/AdminCampaignContent.js, frontend/src/utils/index.js
makes admin page campaign date format not cringe
=> [CHAOS-141] use natural date format for campaign dates on admin page

backend/README.md
=> fix cargo watch run command

backend/server/src/auth.rs, backend/server/src/organisation.rs, frontend/src/components/AdminSideBar/index.jsx
=> [CHAOS-155] Return ID of new org when it is created

frontend/package.json, frontend/src/pages/create_campaign/Campaign/index.tsx, frontend/yarn.lock
fix date pickers for create campaign page because of cringe mui update
=> fix(create_campaign): use @mui/x-date-pickers

frontend/src/App.tsx, frontend/src/components/MessagePopup/index.tsx, frontend/src/components/index.ts, frontend/src/contexts/MessagePopupContext.ts, frontend/src/pages/create_campaign/index.tsx
=> Chaos 160 create message popup component

frontend/src/pages/create_campaign/index.tsx
Default campaign end date 2 weeks from creation
=> Changed default ending date of campaigns

frontend/src/components/CampaignCard/Card.tsx
css grid is cringe on chromium?
=> fix(CampaignCard): limit image height on chromium

backend/server/src/application.rs, backend/server/src/bin.rs, backend/server/src/campaigns.rs, backend/server/src/comment.rs, backend/server/src/organisation.rs, backend/server/src/role.rs, frontend/src/api/index.ts
=> change POST /new to POST /

frontend/src/pages/application_page/index.tsx
While consulting with Michael about an issue he was having I managed to track down the source of the infinite loop :).
=> fix(application_page): fix infinite render loop

frontend/src/api/api.ts, frontend/src/components/Button.tsx, frontend/src/components/Modal/index.tsx, frontend/src/pages/admin/AdminContent/AdminCampaignContent.tsx, frontend/src/pages/admin/AdminContent/index.tsx, frontend/tailwind.config.js
no more accidentally deleting csesoc
=> feat(frontend): add delete confirmation dialogs

frontend/.eslintrc.json, frontend/src/components/Card.tsx, frontend/src/components/Input.tsx, frontend/src/pages/signup/index.tsx
=> feat(frontend): redesign signup page

frontend/src/components/NavBar/AvatarButton.tsx, frontend/src/components/NavBar/index.tsx, frontend/src/components/Transition/index.tsx, frontend/src/pages/dashboard/CampaignGrid/index.tsx, frontend/src/pages/landing/components/Campaigns/Campaign.tsx, frontend/src/pages/landing/components/Campaigns/index.tsx, frontend/src/pages/landing/index.tsx, frontend/src/utils/index.ts
we move the logout button into the popover
https://user-images.githubusercontent.com/25019123/203874611-6c4f670c-fbe6-4491-b8cc-b9ffc991cd21.mp4
=> feat(frontend): add navbar avatar button with popover

frontend/src/components/NavBar/index.tsx
=> feat(navbar): link logo to dashboard when logged in

backend/migrations/2023-02-08-081803_questions/down.sql, backend/migrations/2023-02-08-081803_questions/up.sql, backend/seed_data/src/seed.rs, backend/server/src/campaigns.rs, backend/server/src/database/models.rs, backend/server/src/database/schema.rs
Merge CHAOS-183 into CHAOS-204 so that new question types framework works with common/unique questions.
=> feat: questions shared or all - merge into "new question types"

frontend/src/components/NavBar/index.tsx, frontend/src/pages/landing/components/DashboardButton.tsx, frontend/src/pages/landing/index.tsx
=> feat(frontend): update login/signup buttons to Coming Soon

frontend/src/components/QuestionComponents/Dropdown/index.tsx, frontend/src/components/QuestionComponents/MultiChoice/index.tsx, frontend/src/components/QuestionComponents/MultiSelect/index.tsx, frontend/src/components/QuestionComponents/ShortAnswer/index.tsx, frontend/src/pages/question_components_test/index.tsx, frontend/yarn.lock
- Refactor question components into ShadCN UI components
=> Feat/shad cn UI question components

backend/server/Cargo.toml, backend/server/src/handler/auth.rs, backend/server/src/service/answer.rs, backend/server/src/service/application.rs
feat: Added Cookie header wrapping around token string
fix: Some SQL query error suggested by rust-analyser
=> Chaos 542 auth token set cookie

backend/server/src/handler/organisation.rs, backend/server/src/models/app.rs, backend/server/src/models/organisation.rs
added BE route to get all orgnisations where logged in user is an Admin of
changed get all campaigns route name
=> Get Orgs where User is Admin of
